### ISSUE TITLE
ImportError: cannot import name 'filter'

### ISSUE THREAD

**Issue by golanglang** [alexferl/flask-simpleldap#53]
File "/usr/local/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 6, in <module>
    from ldap import filter as ldap_filter
ImportError: cannot import name 'filter'

**Comment by admiralobvious** [comment]
Is this still valid?

**Comment by nickolay** [comment]
Works for me, for what it's worth! (on Python 3.7.0)

**Comment by greyamigo** [comment]
I am still getting this error 

project has 
black==19.3b0
coverage==5.1
Flask==1.1.2
Flask-Cors==3.0.8
Flask-JWT==0.3.2
Flask-Migrate==2.5.2
flask-simpleldap==1.4.0
Flask-SQLAlchemy==2.4.1
Flask-RESTful==0.3.8
gunicorn==20.0.4
mypy==0.770
pytest==5.4.1
