### ISSUE TITLE
Always saying wrong password

### ISSUE THREAD

**Issue by sameertikoo** [alexferl/flask-simpleldap#79]
![image](https://user-images.githubusercontent.com/15632991/92960446-45637980-f48b-11ea-87af-73880df68e01.png)
I have trying the basic auth example in the repo.
However I am always getting the wrong password issue even after changing it

**Comment by HashBR** [comment]
"Note that with the default value of LDAP_USER_OBJECT_FILTER the login is expected to match the userPrincipalName attribute of the LDAP user, e.g. me@mydomain.com."

So you need to use "11964@domain.com" instead.

**Comment by sameertikoo** [comment]
@HashBR 
Well that saved my life 👍
