### ISSUE TITLE
Flask 3.0 Compatibility

### ISSUE THREAD

**Issue by mike-england** [alexferl/flask-simpleldap#96]
I'm not sure if this project is maintained anymore, but I was trying to get it working with Flask 3 and it seems there's been an API update to an underlying [Werkzeug](https://werkzeug.palletsprojects.com/en/3.0.x/wrappers/#werkzeug.wrappers.Response.www_authenticate) property.  I've decided to simply take a copy of this code and make the required changes in my own project as it's pretty self contained.

If anyone else runs into this issue, the problem is under make_aut_required_response().  It's a one line fix, I've left the original commented out.

```
def make_auth_required_response():
            response = make_response('Unauthorized', 401)
            response.www_authenticate = WWWAuthenticate("basic", {"realm": current_app.config['LDAP_REALM_NAME']})
            #response.www_authenticate.set_basic(current_app.config['LDAP_REALM_NAME'])
            return response
```

You'll also need to import WWWAuthenticate like this:

`from werkzeug.datastructures import WWWAuthenticate`

**Comment by alexferl** [comment]
Fixed in v2.0.0.
